### ISSUE TITLE
Possible to run on Pytorch with CPU support only?

### ISSUE THREAD

**Issue by taewookim** [smivv/pytorch-chexnet#2]
what modifications would i need to make?

**Comment by smivv** [comment]
@taewookim I've tried to run it on cpu, but it does not work, because model was trained in gpu.

**Comment by taewookim** [comment]
really? is that some kind of pytorch limitation? pretty sure in TF, you can train on GPU and run on CPU no problem...

**Comment by smivv** [comment]
@taewookim I tried with no luck, of course you are welcome to pull request with your implementation.

**Comment by taewookim** [comment]
thanks @smivv . will poke around and see if i find anything

**Comment by smivv** [comment]
@taewookim let me know if you need something.
