### ISSUE TITLE
Running the network on test image

### ISSUE THREAD

**Issue by taewookim** [smivv/pytorch-chexnet#4]
1) How do I generate heatmap?

2) how do I interpret the results? I ran one on [this image](https://www.med-ed.virginia.edu/courses/rad/cxr/web%20images/solitary%20nodule%20LUL%20PA.jpg) (xray with nodules detected) and got this result:

> [ { "Atelectasis":0.49452733993530273 }, { "Cardiomegaly":0.6072946786880493 }, { "Effusion":0.5043863654136658 }, { "Infiltration":0.6327313780784607 }, { "Mass":0.4583894908428192 }, { "Nodule":0.3783107101917267 }, { "Pneumonia":0.565626323223114 }, { "Pneumothorax":0.46577414870262146 }, { "Consolidation":0.721723198890686 }, { "Edema":0.27183231711387634 }, { "Emphysema":0.6521075963973999 }, { "Fibrosis":0.3962574005126953 }, { "Pleural_Thickening":0.6883941292762756 }, { "Hernia":0.3340536057949066 } ]

**Comment by smivv** [comment]
1) For heatmap generation you should use [Grad-Cam](https://github.com/kazuto1011/grad-cam-pytorch) algorithm.
2) This values are probability for each of diseases.

**Comment by taewookim** [comment]
Thanks @smivv 
How about bounding boxes / labels? Ideas?

**Comment by smivv** [comment]
Model used here does not assume the presence of bounding boxes.
